version: '3.8'

volumes:
  postgres-data:
  redis-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
